### ISSUE TITLE
GoogleNews on EC2

### ISSUE THREAD

**Issue by claudia0juarez** [HurinHu/GoogleNews#15]
I have been running this script in AWS EC2 through a virtual environment running on python34 and coming back empty; when I run it locally in PyCharm I am getting a result, do you know why is this the case?

import requests
from bs4 import BeautifulSoup
from GoogleNews import GoogleNews

googlenews = GoogleNews()
googlenews.search('forbes')
url = googlenews.getlinks()
name = googlenews.result()
print(url[0])

**Comment by HurinHu** [comment]
The problem is, google knows you are using a cloud server through IP, and it will block the IP as it is recognized as a robot.

Kind Regards,

Hurin Hu
Web Developer
https://hurin.iceloof.com<https://hurin.iceloof.com/>

On 24/02/2020, at 17:08, Claudia <notifications@github.com> wrote:

﻿

I have been running this script in AWS EC2 through a virtual environment running on python34 and coming back empty; when I run it locally in PyCharm I am getting a result, do you know why is this the case?

import requests
from bs4 import BeautifulSoup
from GoogleNews import GoogleNews

googlenews = GoogleNews()
googlenews.search('forbes')
url = googlenews.getlinks()
name = googlenews.result()
print(url[0])

**Comment by claudia0juarez** [comment]
Thanks! Do you know a way to bypass this error?

**Comment by mjlabe** [comment]
I have mine running on Digital Ocean. Maybe they just block AWS?

**Comment by HurinHu** [comment]
If it is not necessary to run on server, you can run it locally and pass the results to the server rather than running on the server directly. And don’t call the method too frequently, it also may cause this issue.

Kind Regards,

Hurin Hu
Web Developer
https://hurin.iceloof.com<https://hurin.iceloof.com/>

On 24/02/2020, at 17:13, Claudia <notifications@github.com> wrote:

﻿

Thanks! Do you know a way to bypass this error?

**Comment by claudia0juarez** [comment]
Thanks mjlabe/Hurin, I do need it to run over EC2 as it needs to run daily on a cron job

**Comment by claudia0juarez** [comment]
BTW I tried running it in GoogleCloud same results
